### ISSUE TITLE
oauth_user_id field different & get auth user

### ISSUE THREAD

**Issue by f80sergeant** [DataHiveDevelopment/Laravel-Introspection#8]
Hi, 
Thanks for your great package.
1. My Passport server returns user id in "sub" property instead of "id" property. Could you give me an explanation ? 
2. In controllers, I want to get all filtered records for authenticated users. I use : Auth::user() to get user id.But I've got always the same user id with two different authenticated users while Introspection package gets good user id...

**Comment by ReArmedHalo** [comment]
Hi! I'll have to dig into this more later but real quick:

1. I can't find it right now, but I am pretty sure that I am returning the same claims Passport does in the `IntrospectionController`. The only thing I believe is different is the `sub` claim. `ID` is the auto-increment (by default) ID of the user model from the database, `sub` is a unique identifier (I prefer UUID) that can be shared with clients so that the client can associate a user to the same user on the Introspection / Authorization server.
https://github.com/DataHiveDevelopment/Laravel-Introspection/blob/d1f912bcbbb935e2d71a01af2183fbb022ae3132/src/Http/Controllers/IntrospectionController.php#L106-L128
2. Can you provide some examples of the code you use and what you get? I'm a bit confused.

P.S: Please note I am still working to properly separate this packages responsibility between auth and resource servers. I apologize for the confusing documentation and I am looking for suggestions on the package and documentation.

**Comment by f80sergeant** [comment]
Thanks.

1. I'll check.
 
2. Example
Controller 
>  public function index()
>  {
>              return Site::with('asset')
>                  ->where('user_id', Auth::user()->id)
>                  ->get();
>   }

Auth::user content:

> Object(App\User)#1248 (29) {
>   ["fillable":protected]=>
>   array(3) {
>     [0]=>
>     string(4) "name"
>     [1]=>
>     string(5) "email"
>     [2]=>
>     string(8) "password"
>   }
>   ["hidden":protected]=>
>   array(2) {
>     [0]=>
>     string(8) "password"
>     [1]=>
>     string(14) "remember_token"
>   }
>   ["casts":protected]=>
>   array(1) {
>     ["email_verified_at"]=>
>     string(8) "datetime"
>   }
>   ["connection":protected]=>
>   string(5) "pgsql"
>   ["table":protected]=>
>   string(5) "users"
>   ["primaryKey":protected]=>
>   string(2) "id"
>   ["keyType":protected]=>
>   string(3) "int"
>   ["incrementing"]=>
>   bool(true)
>   ["with":protected]=>
>   array(0) {
>   }
>   ["withCount":protected]=>
>   array(0) {
>   }
>   ["perPage":protected]=>
>   int(15)
>   ["exists"]=>
>   bool(true)
>   ["wasRecentlyCreated"]=>
>   bool(false)
>   ["attributes":protected]=>
>   array(8) {
>     ["id"]=>
>     int(4)
>     ["name"]=>
>     string(4) "prin"
>     ["email"]=>
>     string(4) "zzzz"
>     ["email_verified_at"]=>
>     NULL
>     ["password"]=>
>     string(4) "xxxx"
>     ["remember_token"]=>
>     NULL
>     ["created_at"]=>
>     string(19) "2020-06-05 15:11:12"
>     ["updated_at"]=>
>     string(19) "2020-06-05 15:11:12"
>   }
>   ["original":protected]=>
>   array(8) {
>     ["id"]=>
>     int(4)
>     ["name"]=>
>     string(4) "prin"
>     ["email"]=>
>     string(4) "zzzz"
>     ["email_verified_at"]=>
>     NULL
>     ["password"]=>
>     string(4) "aaaa"
>     ["remember_token"]=>
>     NULL
>     ["created_at"]=>
>     string(19) "2020-06-05 15:11:12"
>     ["updated_at"]=>
>     string(19) "2020-06-05 15:11:12"
>   }
>   ["changes":protected]=>
>   array(0) {
>   }
>   ["classCastCache":protected]=>
>   array(0) {
>   }
>   ["dates":protected]=>
>   array(0) {
>   }
>   ["dateFormat":protected]=>
>   NULL
>   ["appends":protected]=>
>   array(0) {
>   }
>   ["dispatchesEvents":protected]=>
>   array(0) {
>   }
>   ["observables":protected]=>
>   array(0) {
>   }
>   ["relations":protected]=>
>   array(0) {
>   }
>   ["touches":protected]=>
>   array(0) {
>   }
>   ["timestamps"]=>
>   bool(true)
>   ["visible":protected]=>
>   array(0) {
>   }
>   ["guarded":protected]=>
>   array(1) {
>     [0]=>
>     string(1) "*"
>   }
>   ["rememberTokenName":protected]=>
>   string(14) "remember_token"
>   ["accessToken":protected]=>
>   object(DataHiveDevelopment\Introspection\Token)#1247 (27) {
>     ["casts":protected]=>
>     array(2) {
>       ["scopes"]=>
>       string(5) "array"
>       ["revoked"]=>
>       string(4) "bool"
>     }
>     ["dates":protected]=>
>     array(1) {
>       [0]=>
>       string(10) "expires_at"
>     }
>     ["fillable":protected]=>
>     array(3) {
>       [0]=>
>       string(6) "client"
>       [1]=>
>       string(6) "scopes"
>       [2]=>
>       string(10) "expires_at"
>     }
>     ["timestamps"]=>
>     bool(false)
>     ["connection":protected]=>
>     NULL
>     ["table":protected]=>
>     NULL
>     ["primaryKey":protected]=>
>     string(2) "id"
>     ["keyType":protected]=>
>     string(3) "int"
>     ["incrementing"]=>
>     bool(true)
>     ["with":protected]=>
>     array(0) {
>     }
>     ["withCount":protected]=>
>     array(0) {
>     }
>     ["perPage":protected]=>
>     int(15)
>     ["exists"]=>
>     bool(false)
>     ["wasRecentlyCreated"]=>
>     bool(false)
>     ["attributes":protected]=>
>     array(3) {
>       ["client"]=>
>       int(1)
>       ["scopes"]=>
>       string(4) "[""]"
>       ["expires_at"]=>
>       string(19) "2021-06-05 15:12:06"
>     }
>     ["original":protected]=>
>     array(0) {
>     }
>     ["changes":protected]=>
>     array(0) {
>     }
>     ["classCastCache":protected]=>
>     array(0) {
>     }
>     ["dateFormat":protected]=>
>     NULL
>     ["appends":protected]=>
>     array(0) {
>     }
>     ["dispatchesEvents":protected]=>
>     array(0) {
>     }
>     ["observables":protected]=>
>     array(0) {
>     }
>     ["relations":protected]=>
>     array(0) {
>     }
>     ["touches":protected]=>
>     array(0) {
>     }
>     ["hidden":protected]=>
>     array(0) {
>     }
>     ["visible":protected]=>
>     array(0) {
>     }
>     ["guarded":protected]=>
>     array(1) {
>       [0]=>
>       string(1) "*"
>     }
>   }
> }

**Comment by ReArmedHalo** [comment]
Regarding question 2, how are you identifying users across your platform? If your using the auto-increment ID then it's very possible that you are fetching the wrong user when using Auth::user(). The way I built the introspection to allow you to use the Auth::user() method in APIs depends on you having a central source of truth for users.

Your authorization server will hold the users typically (password, email, UUID most importantly (or some other unique identifier that can be used across platforms)) and then you use something like OAuth to login users from your resource servers and you hold a "stub" of the users (like just the UUID and their name or email, really you can hold and sync whatever details you want, this is just an example).

[See this UUID Setup section in the docs](https://github.com/DataHiveDevelopment/Laravel-Introspection#UUIDSetup) for more details there.

The guard only works for API routes as well as there needs to be a bearer token in the request so we can do the introspection against your authorization server and figure out the local user in your resource server.

See here for how we return the user when using Auth::user():
https://github.com/DataHiveDevelopment/Laravel-Introspection/blob/d1f912bcbbb935e2d71a01af2183fbb022ae3132/src/IntrospectionGuard.php#L52-L111

**Comment by f80sergeant** [comment]
Thank you for your help.
Users are authenticated from the javascript front end by being directly written on the authentication server.Then I pass the bearer token in the header to consume the api of the resource server. 
This process seems to me correct ? 
I thought I would get the user ID from the authentication server (at first); I also understand very well the use of the UUID.

Another question I have is how to synchronize a user at his first connection? It should be possible to have a logic that determines if the authenticated user can access the API of this resource server, right?
How can I access the user method of InstrospectionGuard? sorry I lack of skills on Laravel...

**Comment by ReArmedHalo** [comment]
That sounds correct.

Authorization server issues the access token, you use it against your resource server and the Introspection class will [extract](https://github.com/DataHiveDevelopment/Laravel-Introspection/blob/d1f912bcbbb935e2d71a01af2183fbb022ae3132/src/Introspection.php#L61) the user from the tokens `id` claim. From there, the IntrospectionGuard will try and find the matching user ID, [by default using the UUID column](https://github.com/DataHiveDevelopment/Laravel-Introspection#Overriding) on the User model, from your resource server’s user database and return the model (this is the same thing Passport does, but we modify the way in which it does that due to introspection).

As long as your API configuration is using the introspection guard, the Auth::user() should return the user associated with the bearer token that was provided.

As for synchronizing users, this is all up to your implementation of how you want to log users into your resource servers. This package doesn’t provide that functionality. I personally find just doing OAuth using Passport on the authorization server and the Passport Socialite driver works well. This is similar to how you would enable “Login with Facebook/Twitter/Google” etc functionality. The way I’ve been handling this is that the users can’t use the API on the resource servers if they haven’t signed in via the web at least once on the resource server to “register” them with the application.

No worries :) I suck at writing documentation that makes sense.

**Comment by ReArmedHalo** [comment]
I'm going to close this for now for two reasons:

1) Dev builds of the new packages are live, this repo will be getting archived soon after testing concludes
2) I haven't heard anything further from you in 21 days, marking as stale

Feel free to re-open if you have any further questions. And check out the new packages and documentation! Feedback appreciated over there :)
